name: PostMerge Push Docker

on:
  # This workflow only runs when triggered by a push event also can be manually triggered
  workflow_dispatch:
  push:
    # Only runs when take push events on certain branch
    branches: [ linux-6.6 ]
    # Only runs take push changes Dockerfile
    paths:
      - 'docker/xuantie-qemu/Dockerfile'

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v5
        with:
          file: ./docker/xuantie-qemu/Dockerfile
          tags: ghcr.io/ruyisdk/linux-xuantie-kernel/xuantie-qemu:latest
          push: true
